nama            = input("Nama                   : ")
nim             = input("NIM                    : ")
kelas           = input("Kelas Paralel          : ")
tempat_lahir    = input("Tempat/Tanggal Lahir   : ")
alamat          = input("Alamat                 : ")
hobby           = input("Hobby                  : ")
no_hp           = input("No. HP                 : ")

print(f"Nama                   : {nama}")
print(f"NIM                    : {nim}")
print(f"Kelas Paralel          : {kelas}")
print(f"Tempat/Tanggal Lahir   : {tempat_lahir}")
print(f"Alamat                 : {alamat}")
print(f"Hobby                  : {hobby}")
print(f"No. HP                 : {no_hp}")