print("##############################")
print("#                            #")
print("#    Akhmad Daffa Azzikri    #") 
print("#       2410817110002        #") 
print("#                            #") 
print("##############################") 